================================================ test session starts ================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/stidsem4/iut/2021/controle/ange-vivien.bathossi/c16_03
collected 7 items

test_16_03.py F.FFFFF                                                                                         [100%]

===================================================== FAILURES ======================================================
_______________________________________________ Test1603sute.test_10 ________________________________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_10>

    def test_10(self):
        try:
>           from .main  import Note

test_16_03.py:94: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    note1 = ('eleve1', 'math', 13)
    note2 = ('eleve1', 'physique', 15)
    note3 = ('eleve1', 'math', 13)
    note4 = ('eleve1', 'eco', 12)
    note5 = ('eleve1', 'eco', 13)
    note6 = ('eleve1', 'math', 12)
    note7 = ('eleve2', 'math', 13)
    note8 = ('eleve2', 'math', 14)
    
    notes = [note1, note2, note3, note4, note5, note6,note7,note8]
    
    moyelev1 = (notes[0][2]+notes[1][2]+notes[2][2]+notes[3][2]+notes[4][2]+notes[5][2])/6
    print("la moyenne de l'élévé 1 = ",moyelev1)
    #4)b
    moyelev1_math = (notes[0][2]+notes[2][2]+notes[5][2])/3
    print("la moyenne de l'élévé 1 en math = ",moyelev1_math)
    #4)c
    notes_tuples = [note1, note2, note3, note4, note5, note6,note7,note8]
    def moyenne():
        eleve = input("Entrez le nom de l'élève: ")
        matiere  = input("Choisissez la matière: ")
        cpt = 0
        moyenne = 0
    
        for i in range(8):
            if(notes_tuples[i][0] == eleve):
                if(notes_tuples[i][1] == matiere):
                    moyenne += notes_tuples[i][2]
                    cpt += 1
        moyenne = moyenne/cpt
        print(moyenne)
    
>   moyenne()

main.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def moyenne():
>       eleve = input("Entrez le nom de l'élève: ")

main.py:20: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.capture.DontReadFromInput object at 0x7f52a22a9970>, args = ()

    def read(self, *args):
>       raise OSError(
            "pytest: reading from stdin while output is captured!  Consider using `-s`."
        )
E       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.

/home/stidsem4/.local/lib/python3.9/site-packages/_pytest/capture.py:217: OSError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_10>

    def test_10(self):
        try:
            from .main  import Note
        except:
>          assert False
E          AssertionError: assert False

test_16_03.py:96: AssertionError
----------------------------------------------- Captured stdout call ------------------------------------------------
la moyenne de l'élévé 1 =  13.0
la moyenne de l'élévé 1 en math =  12.666666666666666
Entrez le nom de l'élève: 
________________________________________________ Test1603sute.test_4 ________________________________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_4>

    def test_4(self):
        try:
>           from main import moyenne_tuples
E           ImportError: cannot import name 'moyenne_tuples' from 'main' (/home/stidsem4/iut/2021/controle/ange-vivien.bathossi/main.py)

test_16_03.py:16: ImportError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_4>

    def test_4(self):
        try:
            from main import moyenne_tuples
        except ImportError:
            try:
>               from .main import moyenne_tuple as moyenne_tuples

test_16_03.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
main.py:33: in <module>
    moyenne()
main.py:20: in moyenne
    eleve = input("Entrez le nom de l'élève: ")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.capture.DontReadFromInput object at 0x7f52a22a9970>, args = ()

    def read(self, *args):
>       raise OSError(
            "pytest: reading from stdin while output is captured!  Consider using `-s`."
        )
E       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.

/home/stidsem4/.local/lib/python3.9/site-packages/_pytest/capture.py:217: OSError
----------------------------------------------- Captured stdout call ------------------------------------------------
la moyenne de l'élévé 1 =  13.0
la moyenne de l'élévé 1 en math =  12.666666666666666
Entrez le nom de l'élève: 
________________________________________________ Test1603sute.test_5 ________________________________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_5>

    def test_5(self):
        try:
>           from .main  import Note, onotes

test_16_03.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    note1 = ('eleve1', 'math', 13)
    note2 = ('eleve1', 'physique', 15)
    note3 = ('eleve1', 'math', 13)
    note4 = ('eleve1', 'eco', 12)
    note5 = ('eleve1', 'eco', 13)
    note6 = ('eleve1', 'math', 12)
    note7 = ('eleve2', 'math', 13)
    note8 = ('eleve2', 'math', 14)
    
    notes = [note1, note2, note3, note4, note5, note6,note7,note8]
    
    moyelev1 = (notes[0][2]+notes[1][2]+notes[2][2]+notes[3][2]+notes[4][2]+notes[5][2])/6
    print("la moyenne de l'élévé 1 = ",moyelev1)
    #4)b
    moyelev1_math = (notes[0][2]+notes[2][2]+notes[5][2])/3
    print("la moyenne de l'élévé 1 en math = ",moyelev1_math)
    #4)c
    notes_tuples = [note1, note2, note3, note4, note5, note6,note7,note8]
    def moyenne():
        eleve = input("Entrez le nom de l'élève: ")
        matiere  = input("Choisissez la matière: ")
        cpt = 0
        moyenne = 0
    
        for i in range(8):
            if(notes_tuples[i][0] == eleve):
                if(notes_tuples[i][1] == matiere):
                    moyenne += notes_tuples[i][2]
                    cpt += 1
        moyenne = moyenne/cpt
        print(moyenne)
    
>   moyenne()

main.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def moyenne():
>       eleve = input("Entrez le nom de l'élève: ")

main.py:20: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.capture.DontReadFromInput object at 0x7f52a22a9970>, args = ()

    def read(self, *args):
>       raise OSError(
            "pytest: reading from stdin while output is captured!  Consider using `-s`."
        )
E       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.

/home/stidsem4/.local/lib/python3.9/site-packages/_pytest/capture.py:217: OSError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_5>

    def test_5(self):
        try:
            from .main  import Note, onotes
        except:
>           assert False
E           AssertionError: assert False

test_16_03.py:35: AssertionError
----------------------------------------------- Captured stdout call ------------------------------------------------
la moyenne de l'élévé 1 =  13.0
la moyenne de l'élévé 1 en math =  12.666666666666666
Entrez le nom de l'élève: 
________________________________________________ Test1603sute.test_6 ________________________________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_6>

    def test_6(self):
>       from .main import Note, onotes

test_16_03.py:41: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
main.py:33: in <module>
    moyenne()
main.py:20: in moyenne
    eleve = input("Entrez le nom de l'élève: ")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.capture.DontReadFromInput object at 0x7f52a22a9970>, args = ()

    def read(self, *args):
>       raise OSError(
            "pytest: reading from stdin while output is captured!  Consider using `-s`."
        )
E       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.

/home/stidsem4/.local/lib/python3.9/site-packages/_pytest/capture.py:217: OSError
----------------------------------------------- Captured stdout call ------------------------------------------------
la moyenne de l'élévé 1 =  13.0
la moyenne de l'élévé 1 en math =  12.666666666666666
Entrez le nom de l'élève: 
________________________________________________ Test1603sute.test_8 ________________________________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_8>

    def test_8(self):
        try:
>           from .main import Note

test_16_03.py:67: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
main.py:33: in <module>
    moyenne()
main.py:20: in moyenne
    eleve = input("Entrez le nom de l'élève: ")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.capture.DontReadFromInput object at 0x7f52a22a9970>, args = ()

    def read(self, *args):
>       raise OSError(
            "pytest: reading from stdin while output is captured!  Consider using `-s`."
        )
E       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.

/home/stidsem4/.local/lib/python3.9/site-packages/_pytest/capture.py:217: OSError
----------------------------------------------- Captured stdout call ------------------------------------------------
la moyenne de l'élévé 1 =  13.0
la moyenne de l'élévé 1 en math =  12.666666666666666
Entrez le nom de l'élève: 
________________________________________________ Test1603sute.test_9 ________________________________________________

self = <c16_03.test_16_03.Test1603sute testMethod=test_9>

    def test_9(self):
        try:
>           from .main  import Note

test_16_03.py:87: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    note1 = ('eleve1', 'math', 13)
    note2 = ('eleve1', 'physique', 15)
    note3 = ('eleve1', 'math', 13)
    note4 = ('eleve1', 'eco', 12)
    note5 = ('eleve1', 'eco', 13)
    note6 = ('eleve1', 'math', 12)
    note7 = ('eleve2', 'math', 13)
    note8 = ('eleve2', 'math', 14)
    
    notes = [note1, note2, note3, note4, note5, note6,note7,note8]
    
    moyelev1 = (notes[0][2]+notes[1][2]+notes[2][2]+notes[3][2]+notes[4][2]+notes[5][2])/6
    print("la moyenne de l'élévé 1 = ",moyelev1)
    #4)b
    moyelev1_math = (notes[0][2]+notes[2][2]+notes[5][2])/3
    print("la moyenne de l'élévé 1 en math = ",moyelev1_math)
    #4)c
    notes_tuples = [note1, note2, note3, note4, note5, note6,note7,note8]
    def moyenne():
        eleve = input("Entrez le nom de l'élève: ")
        matiere  = input("Choisissez la matière: ")
        cpt = 0
        moyenne = 0
    
        for i in range(8):
            if(notes_tuples[i][0] == eleve):
                if(notes_tuples[i][1] == matiere):
                    moyenne += notes_tuples[i][2]
                    cpt += 1
        moyenne = moyenne/cpt
        print(moyenne)
    
>   moyenne()

main.py:33: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def moyenne():
>       eleve = input("Entrez le nom de l'élève: ")

main.py:20: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.capture.DontReadFromInput object at 0x7f52a22a9970>, args = ()

    def read(self, *args):
>       raise OSError(
            "pytest: reading from stdin while output is captured!  Consider using `-s`."
        )
E       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.

/home/stidsem4/.local/lib/python3.9/site-packages/_pytest/capture.py:217: OSError

During handling of the above exception, another exception occurred:

self = <c16_03.test_16_03.Test1603sute testMethod=test_9>

    def test_9(self):
        try:
            from .main  import Note
        except:
>          assert False
E          AssertionError: assert False

test_16_03.py:89: AssertionError
----------------------------------------------- Captured stdout call ------------------------------------------------
la moyenne de l'élévé 1 =  13.0
la moyenne de l'élévé 1 en math =  12.666666666666666
Entrez le nom de l'élève: 
============================================== short test summary info ==============================================
FAILED test_16_03.py::Test1603sute::test_10 - AssertionError: assert False
FAILED test_16_03.py::Test1603sute::test_4 - OSError: pytest: reading from stdin while output is captured!  Consid...
FAILED test_16_03.py::Test1603sute::test_5 - AssertionError: assert False
FAILED test_16_03.py::Test1603sute::test_6 - OSError: pytest: reading from stdin while output is captured!  Consid...
FAILED test_16_03.py::Test1603sute::test_8 - OSError: pytest: reading from stdin while output is captured!  Consid...
FAILED test_16_03.py::Test1603sute::test_9 - AssertionError: assert False
============================================ 6 failed, 1 passed in 0.17s ============================================
